# Generated by Django 3.0.1 on 2021-01-28 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sentiment_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment_records',
            name='sentiment_polarity',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]