# Generated by Django 3.0.1 on 2021-02-11 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210211_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment_records',
            name='sentiment_polarity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sentiment_records',
            name='sentiment_subjectivity',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
