# Generated by Django 3.0.1 on 2021-03-10 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20210213_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='likes',
            field=models.ManyToManyField(related_name='songs_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
