# Generated by Django 3.0.1 on 2021-03-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_songs_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='songs_id',
            field=models.TextField(db_index=True, max_length=100),
        ),
    ]
